# Generated by Django 4.0.4 on 2022-05-28 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_2FA_enabled',
            field=models.BooleanField(default=False, help_text='Designates whether 2FA enabled.', verbose_name='2FA status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09121234567'.", regex='^\\+989\\d{9}$')]),
        ),
    ]
