# Generated by Django 4.0.4 on 2022-05-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_managers_customuser_is_2fa_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='Designates whether the email verified.', verbose_name='email status'),
        ),
    ]
